[colors.primary]
background = "#070e10"
foreground = "#c1c2c3"

[colors.cursor]
text = "#070e10"
cursor = "#c1c2c3"

[colors.vi_mode_cursor]
text = "#070e10"
cursor = "#c1c2c3"

[colors.search.matches]
foreground = "#070e10"
background = "#c1c2c3"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#566669"
background = "#c1c2c3"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#070e10"
red = "#053b78"
green = "#06717e"
yellow = "#166dba"
blue = "#4374c7"
magenta = "#149b92"
cyan = "#52a7be"
white = "#c1c2c3"

[colors.bright]
black = "#566669"
red = "#053b78"
green = "#06717e"
yellow = "#166dba"
blue = "#4374c7"
magenta = "#149b92"
cyan = "#52a7be"
white = "#c1c2c3"

[colors.dim]
black = "#c1c2c3"
red = "#053b78"
green = "#149b92"
yellow = "#166dba"
blue = "#4374c7"
magenta = "#06717e"
cyan = "#52a7be"
white = "#566669"

