[colors]
background = '#070e108e'
black = '#070e10'
blue = '#053b78'
cursor = '#c1c2c3'
cyan = '#06717e'
foreground = '#c1c2c3'
green = '#166dba'
magenta = '#4374c7'
red = '#149b92'
tabs = '#c1c2c3'
tabs-active = '#52a7be'
white = '#c1c2c3'
yellow = '#c1c2c3'
dim-black = '#070e108e'
dim-blue = '#053b788e'
dim-cyan = '#06717e8e'
dim-foreground = '#c1c2c38e'
dim-green = '#166dba8e'
dim-magenta = '#4374c78e'
dim-red = '#149b928e'
dim-white = '#52a7be8e'
dim-yellow = '#c1c2c38e'
light-black = '#053b78'
light-blue = '#06717e'
light-cyan = '#166dba'
light-foreground = '#4374c7'
light-green = '#149b92'
light-magenta = '#52a7be'
light-red = '#c1c2c3'
light-white = '#053b78'
light-yellow = '#06717e'
