--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ladyterror/wave2.png"

-- Special
background="#070e10"
foreground="#c1c2c3"
cursor="#c1c2c3"

-- Colors
color0="#070e10"
color1="#053b78"
color2="#06717e"
color3="#166dba"
color4="#4374c7"
color5="#149b92"
color6="#52a7be"
color7="#c1c2c3"
color8="#566669"
color9="#053b78"
color10="#06717e"
color11="#166dba"
color12="#4374c7"
color13="#149b92"
color14="#52a7be"
color15="#c1c2c3"
