# Shell variables
# Generated by 'wal'
wallpaper="/home/ladyterror/wave2.png"

# Special
background='#070e10'
foreground='#c1c2c3'
cursor='#c1c2c3'

# Colors
color0='#070e10'
color1='#053b78'
color2='#06717e'
color3='#166dba'
color4='#4374c7'
color5='#149b92'
color6='#52a7be'
color7='#c1c2c3'
color8='#566669'
color9='#053b78'
color10='#06717e'
color11='#166dba'
color12='#4374c7'
color13='#149b92'
color14='#52a7be'
color15='#c1c2c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
